routes/web.php
<?php
use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;

Route::get('/', function() {
    return redirect(route('frontend.homes'));
});

Route::get('/frontend', function() {
    return redirect(route('frontend.homes'));
});
Route::get('/send-mail', function () {
 
    Mail::to('newuser@example.com')->send(new MailtrapExample()); 
 
    return 'A message has been sent to Mailtrap!';
 
});

Route::name('frontend.')->prefix('frontend')->group(function() {

    Route::get('homes', 'frontend\HomesController')->name('homes');
   

    Route::get('eventdetail', 'frontend\EventdetailController@index')->name('eventdetail');
    Route::get('hallabout', 'frontend\HallaboutController@index')->name('hallabout');



    Route::get('contact', 'frontend\ContactController@index')->name('contact');

    Route::get('frontend/admin/dashboard', 'DashboardController@index')->middleware('auth')->name('admin.dashboard');

    Route::get('about', 'frontend\AboutController@index')->name('about');
      Route::get('language', 'frontend\LanguageController@index')->name('language');
    
    Route::get('lang/{locale}', 'frontend\LanguageController@lang');
      
});

Route::get('home', function() {
    return redirect(route('admin.dashboard'));
});

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {

    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
   ]);

    Route::resource('event', 'EventTypeController', [
        'names' => [
            'index' => 'event'
        ]
    ]);
    

    Route::resource('eventhall', 'EventHallController', [
        'names' => [
            'index' => 'eventhall'
        ]
    ]);
     Route::post('event_update', 'EventHallController@update')->name('eventhall_update.update');

   Route::resource('state', 'StateController', [
        'names' => [
            'index' => 'state'
        ]

    ]);
   Route::resource('townships', 'TownshipController', [
        'names' => [
            'index' => 'townships'
        ]
    
    ]);

    Route::resource('city', 'CityController', [
        'names' => [
            'index' => 'city'
        ]
    ]);


    Route::resource('contact','ContactController', [

        'names' => [
            'index' => 'contact'
        ]
    ]);
Route::get('googlemap', 'ContactController@map');

Route::get('googlemap/direction', 'ContactController@direction');

    Route::resource('address', 'AddressController', [
        'names' => [
            'index' => 'address'
                
        ]
    ]);
        

    Route::resource('hall', 'HallController', [
        'names' => [
            'index' => 'hall'
        ]
    ]);
    
    Route::post('hall_update', 'HallController@update')->name('hall_update.update');



 });







Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

Route::name('js.')->group(function() {
    Route::get('dynamic.js', 'JsController@dynamic')->name('dynamic');
});

// Get authenticated user
Route::get('users/auth', function() {
    return response()->json(['user' => Auth::check() ? Auth::user() : false]);
});

app/Http/Controllers/CityController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\MyLibs\Repositories\CityRepository;
use App\MyLibs\Repositories\StateRepository;
use Grimthorr\LaravelToast\Toast;
use Illuminate\Support\Facades\DB;

class CityController extends Controller
{
  public function __construct(CityRepository $cityRepo , StateRepository $stateRepo)
  {
    $this->cityRepo=$cityRepo;
        $this->stateRepo=$stateRepo;
       // $this->middleware('acityRepouth');

  }
    public function create()
    {
        $statedata = [];
        $statedata =$this->stateRepo->getAll();
       return view('admin.city.create',compact('statedata'));
        
    }
   public function store(Request $request)

    {

      $data = $request->all();

      $cities=explode(',', $data['city_name']);

      foreach ($cities as $key => $value)
      {
        $city['state_id'] =$data['state_id'];
        
        $state = DB::table('states')
                ->where('states.id','=',$city['state_id'])
                ->value('state_name');
             
        $ans = DB::table('cities')->where('cities.state_id','=',$city['state_id'])  
                                  ->where('cities.city_name','=',$value)->first() ;
        dd($ans);
        if(!is_null($ans))  
        {
          return back()->with('error','State Name "'. $state .'"' .' and City Name "'.$value .'"'.' has been inserted.');
        }                      
      }
      foreach ($cities as $key => $value) 
      {
        $city['state_id'] =$data['state_id'];
        $city['city_name'] =$value;
        $this->cityRepo->create($city);
      }
        return back()->with('info','City is successfully save!');
        return redirect()->back()->withInput();

    }


    
   

    public function  index(Request $request)

    {
      
        $data = DB::table('cities')
       ->join('states', 'states.id', '=', 'cities.state_id')
       ->select('cities.id','states.state_name', 'cities.city_name','cities.created_at','cities.updated_at')
       ->get();
        
        return view('admin.city.index',compact('data'));
    }
    
    public function edit($city_id)
    {
       
       $statedata = [];
       $statedata =$this->stateRepo->getAll();
       $edit_states=$this->cityRepo->getById($city_id);

         return view('admin.city.edit', compact('edit_states','statedata'));
         
    }
    public function show($city_id,Request $request)
    {
      
      
           $data=$request->all();
         
           $data=array_except($data,['$city_id']);
            $this->cityRepo->update($data,$city_id);
           
        
        return back()->with('info','City is successfully update!');
        return redirect()->back()->withInput();
    }
    public function destroy($city_id)
    {
        
        $this->cityRepo->delete($city_id);

            return back()->with('info','City is successfully delete!');
            return redirect()->back()->withInput();
 }
}

resources/views/admin/city/create.blade.php
@extends('layouts.admin-master')

@section('title')
Manage Users
@endsection
@section('content')
<section class="section">
  <div class="section-header">
    <h1>Manage Cities</h1>
  </div>
  <div class="section-body">

    <div class="card">
      <!-- card header -->
      <div class="card-header">

        <!-- card title -->

        <h4>Add a New City</h4>
        <div class="card-header-action" >
        <a href="{{route('admin.city')}}" class="btn btn-primary">CityList</a>
        </div>

      </div>
      
      <!-- card body -->
     

    @if(Session::has('toasts'))
  @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      {{ $toast['message'] }}
    </div>
  @endforeach
@endif

    @if($message = Session::get('info'))
      <div class = "alert alert-info alert-block">
      <strong>{{$message}}</strong>
      </div>
    @endif  

@if($message = Session::get('error'))
      <div class = "alert alert-danger alert-block">
      <strong>{{$message}}</strong>
      </div>
    @endif 

    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form  method="post" action="{{route('admin.city.store')}}">
           <div class="card-body">
          <div class="form-group row mb-4">
              @csrf
              <label class = "col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">State Name:</label>
              <div class="col-sm-12 col-md-7">
              <select name="state_id" class="form-control">
                @foreach($statedata as $state)
                <option value ="{{$state->id}}">
                  {{$state->state_name}}
                </option>
                @endforeach
              </select>
          </div> 
           </div>
          
          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">City Name:</label>
              <div class ="col-sm-12 col-md-7">
               <textarea class="form-control" rows="5" id="city_name" name="city_name" placeholder="Enter City"/></textarea>
             </div>
          </div>
       
          
            <div class="form-group row mb-4">
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name"></label>
            <div class ="col-sm-12 col-md-3">

            <button type="submit" class="btn btn-primary">Save</button>
            <input type="button" value="Cancel" class="btn btn-danger" onclick="clearText()"/>
         </div>
          </div> 
        </form>
  </div>
</div></div></div>
<script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>
<script>
  function clearText(){
    document.getElementById('city_name').value="";
  }
</script>

@endsection

resources/views/admin/city/edit.blade.php
<!-- edit.blade.php -->

@extends('layouts.admin-master')

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Manage Cities</h1>
  </div>
 <div class="card">
      <!-- card header -->
      <div class="card-header">
        <!-- card title -->
        <h4>Edit Form</h4>
        <div class="card-header-action">

          <a href="{{ route('admin.city')}}" class="btn btn-primary">CityList</a></div>

      </div>
     
     @if(Session::has('toasts'))
  @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      {{ $toast['message'] }}
    </div>
  @endforeach
@endif

    @if($message = Session::get('info'))
    <div class = "alert alert-info alert-block">
      <strong>{{$message}}</strong>
      </div>
      @endif 
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif

      <form method="Patch" action="{{ route('admin.city.update',['id'=>$edit_states->id])}}">

           <div class="card-body">
          <div class="form-group row mb-4">
              @csrf
              <label class = "col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">State Name:</label>
               <div class="col-sm-12 col-md-7">
              <select name="state_id" class="form-control">
                @foreach($statedata as $state)
                <option value="{{$state->id}}" {{ $state->id === $edit_states->state_id ? 'selected' : '' }} >
                  {{$state->state_name}}
                </option>
                @endforeach
              </select>
          </div> 
        </div>
          
          <div class="form-group row mb-4">
             @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">City Name:</label>
              <div class ="col-sm-12 col-md-7">
              <input type="text" class="form-control" name="city_name" value="{{$edit_states->city_name}}"/>
          </div>
        </div>
          <div class="form-group row mb-4">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name"></label>
              <div class ="col-sm-12 col-md-7">
              <button type="submit" class="btn btn-primary">Update City</button>
        </div>
      </div>
      </form>
  </div>
</div>
<script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>
@endsection

resources/views/admin/city/index.blade.php
<!-- index.blade.php -->

@extends('layouts.admin-master')

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Manage Cities</h1>
  </div>
 <div class="card">
      <!-- card header -->
      <div class="card-header">
        <!-- card title -->
        <h4>City List</h4>
        <div class="card-header-action">
          <a href="{{ route('admin.city.create')}}" class="btn btn-primary">Add<i class="fas fa-plus"></i></a></div>
      </div>
<div class="card-body">
  @if($message = Session::get('info'))
    <div class = "alert alert-info alert-block">
      <button type = "button" class="close" data-dismiss = "alert">x</button>
      <strong>{{$message}}</strong>
      </div>
      @endif  

       @if(Session::has('toasts'))
  @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

      {{ $toast['message'] }}
    </div>
  @endforeach
@endif 
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif

   <div style="width:100%;height:100%;overflow-x: scroll;overflow-y:hidden";>
  <table class="table table-striped">

 

    <thead>
        <tr>
          
          <td>State Name</td>
          <td>City Name</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
       @foreach($data as $city)
        
        <tr>
            <td>{{$city->state_name}}</td>
            <td>{{$city->city_name}}</td>

            <td><a href="javascript:;" data-toggle="modal" onclick="deleteData({{$city->id}})" 
              data-target="#DeleteModal" class="btn btn-danger"><i class="fa fa-trash"></i> </a>
              <a href="{{ route('admin.city.edit',$city->id)}}" class="btn btn-primary"><i class='fas fa-edit'></i></a>  
            </td>

            
</tr>
@endforeach
            
        
    </tbody>
  </table>
</div>
</section>


<div id="DeleteModal" class="modal fade " role="dialog">
   <div class="modal-dialog modal-sm">
     <!-- Modal content-->
     <form action="" id="deleteForm" method="post">
         <div class="modal-content">
             <div class="modal-header bg-danger">
              <h6 class="modal-title text-center">DELETE CONFIRMATION</h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                 
             </div>
             <div class="modal-body">
                 {{ csrf_field() }}
                 {{ method_field('DELETE') }}
                 <p class="text-center">Are you sure want to delete ?</p>
             </div>
             <div class="modal-footer">
                 <center>
                     <input type="hidden" name="city_id" id="city_id">
                     <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">OK</button>
                     <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                 </center>
             </div>
         </div>
     </form>
   </div>
 </div>


   <script type="text/javascript">
     function deleteData(id)
     {
         var id = id;
         var url = '{{ route("admin.city.destroy",":city_id") }}';
         url = url.replace(':city_id', id);
         $("#deleteForm").attr('action', url);
         document.getElementById('city_id').vaule =id;
     }

     function formSubmit()
     {
         $("#deleteForm").submit();
     }
  </script>
  <script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>

@endsection