routes/web.php
<?php
use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;

Route::get('/', function() {
    return redirect(route('frontend.homes'));
});

Route::get('/frontend', function() {
    return redirect(route('frontend.homes'));
});
Route::get('/send-mail', function () {
 
    Mail::to('newuser@example.com')->send(new MailtrapExample()); 
 
    return 'A message has been sent to Mailtrap!';
 
});

Route::name('frontend.')->prefix('frontend')->group(function() {

    Route::get('homes', 'frontend\HomesController')->name('homes');
   

    Route::get('eventdetail', 'frontend\EventdetailController@index')->name('eventdetail');
    Route::get('hallabout', 'frontend\HallaboutController@index')->name('hallabout');



    Route::get('contact', 'frontend\ContactController@index')->name('contact');

    Route::get('frontend/admin/dashboard', 'DashboardController@index')->middleware('auth')->name('admin.dashboard');

    Route::get('about', 'frontend\AboutController@index')->name('about');
      Route::get('language', 'frontend\LanguageController@index')->name('language');
    
    Route::get('lang/{locale}', 'frontend\LanguageController@lang');
      
});

Route::get('home', function() {
    return redirect(route('admin.dashboard'));
});

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {

    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
   ]);

    Route::resource('event', 'EventTypeController', [
        'names' => [
            'index' => 'event'
        ]
    ]);
    

    Route::resource('eventhall', 'EventHallController', [
        'names' => [
            'index' => 'eventhall'
        ]
    ]);
     Route::post('event_update', 'EventHallController@update')->name('eventhall_update.update');

   Route::resource('state', 'StateController', [
        'names' => [
            'index' => 'state'
        ]

    ]);
   Route::resource('townships', 'TownshipController', [
        'names' => [
            'index' => 'townships'
        ]
    
    ]);

    Route::resource('city', 'CityController', [
        'names' => [
            'index' => 'city'
        ]
    ]);


    Route::resource('contact','ContactController', [

        'names' => [
            'index' => 'contact'
        ]
    ]);
Route::get('googlemap', 'ContactController@map');

Route::get('googlemap/direction', 'ContactController@direction');

    Route::resource('address', 'AddressController', [
        'names' => [
            'index' => 'address'
                
        ]
    ]);
        

    Route::resource('hall', 'HallController', [
        'names' => [
            'index' => 'hall'
        ]
    ]);
    
    Route::post('hall_update', 'HallController@update')->name('hall_update.update');



 });







Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

Route::name('js.')->group(function() {
    Route::get('dynamic.js', 'JsController@dynamic')->name('dynamic');
});

// Get authenticated user
Route::get('users/auth', function() {
    return response()->json(['user' => Auth::check() ? Auth::user() : false]);
});

app/Http/Controllers/EventHallController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\MyLibs\Models;
use App\MyLibs\Repositories\HallRepository;
use App\MyLibs\Repositories\EventTypeRepository;
use App\MyLibs\Repositories\EventHallRepository;
use Grimthorr\LaravelToast\Toast;
use Illuminate\Support\Facades\DB;


class EventHallController extends Controller
{
    public function __construct(EventHallRepository $eventhallRepo ,HallRepository $hallRepo ,EventTypeRepository $eventTypeRepo)
	{
		    $this->eventhallRepo=$eventhallRepo;
        $this->hallRepo=$hallRepo;
        $this->eventTypeRepo=$eventTypeRepo;

	}
    public function create()
    {
        $halldata = [];
        $halldata =$this->hallRepo->getAll();
        $eventdata = [];
        $eventdata =$this->eventTypeRepo->getAll();
    	return view('admin.eventhall.create', compact('halldata','eventdata'));

    }
    
    public function store(Request $request)
    {
    	
        
    	$validatedData=$request->validate([
      'description' => 'required',
      
          'image' => 'required',
        ]);


          $data = $request->all();
          

          $image = $request->file('image');
          $new_name=rand() . '.' . $image->getClientOriginalExtension();
          $image->move(public_path('images'),$new_name);
          $form_data=array(
            'hall_id'=>$request->hall_id,
            'eventType_id'=>$request->eventType_id,
             'description' =>$request->description,
            'image'=>$new_name,
            );

       $this->eventhallRepo->create($form_data);

       return back()->with('info','Hall_Event is successfully save!');
       return redirect()->back()->withInput();
    
    }


    public function index(Request $request)
    {
    	
        $data = DB::table('event_type_halls')
       ->join('halls', 'halls.id', '=', 'event_type_halls.hall_id')
       ->join('event_types', 'event_types.id', '=', 'event_type_halls.eventType_id')
       ->select('event_type_halls.id','halls.hall_name','event_type_halls.image' ,'event_types.event_name','event_type_halls.description')
       ->get();
        
        return view('admin.eventhall.index',compact('data'));
    }
    public function edit($eventhall_id)
    {
       
       $halldata = [];
        $halldata =$this->hallRepo->getAll();
        $eventdata = [];
        $eventdata =$this->eventTypeRepo->getAll();
       $edit_hallevents=$this->eventhallRepo->getById($eventhall_id);

         return view('admin.eventhall.edit', compact('edit_hallevents','halldata','eventdata'));
         
    }
 public function update(Request $request)
           { 
            
             $eventhall_id=$request->id;
              $image_name=$request->hidden_image;
              $image=$request->file('image');
              if($image==''){
                  $form_data=array(
                   'hall_id'=>$request->hall_id,
                    'eventType_id'=>$request->eventType_id,
                    'description'=>$request->description,
                    'image'=>$image_name,
                  );
              }
              if($image!=''){
                $imagenew=rand().'.'.$image->getClientOriginalExtension();
                $image->move(public_path('images'),$imagenew);
                $image_path = public_path().'/images/'.$image_name;
                unlink($image_path);
                $this->eventhallRepo->delete($image_name);
                $form_data=array(
                    'hall_id'=>$request->hall_id,
                    'eventType_id'=>$request->eventType_id,
                    'description'=>$request->description,
                    'image'=>$imagenew,
                );
            }
            
              $form_data=array_except($form_data,['$eventhall_id']);
            $this->eventhallRepo->update($form_data,$eventhall_id);
           
        
        return back()->with('info','Hall_Event is successfully update!');
        return redirect()->back()->withInput();
           }



    public function destroy($eventhall_id)
    {
       $data=$this->eventhallRepo->getById($eventhall_id);
        $image_name=$data->image;
        $image_path = public_path().'/images/'.$image_name;

        unlink($image_path);

        $this->eventhallRepo->delete($eventhall_id,$image_name);
        
        return back()->with('info','Hall_Event is successfully delete!');
             return redirect()->back()->withInput();
 }
}

resources/views/admin/eventhall/create.blade.php
@extends('layouts.admin-master') 

@section('content')

<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">

   
<section class="section">
  <div class="section-header">
    <h1>Manage Hall_Events</h1>
  </div>
  <div class="section-body">

    <div class="card">
      <!-- card header -->
      <div class="card-header">

        <!-- card title -->
        <h4>Hall_Event Form</h4>
        <div class="card-header-action">
          <a href="{{ route('admin.eventhall')}}" class="btn btn-primary">HallEventList</a>
        </div>
      </div>
      <!-- card body -->
      <div class="card-body">

      @if(Session::has('toasts'))
      @foreach(Session::get('toasts') as $toast)
      <div class="alert alert-{{ $toast['level'] }}">
      {{ $toast['message'] }}
      </div>
      @endforeach
      @endif

      @if($message = Session::get('info'))
      <div class = "alert alert-info alert-block">
      <strong>{{$message}}</strong>
      </div>
      @endif  
    
      @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
      @endif
     
         <form  method="post" action="{{route('admin.eventhall.store')}}" enctype="multipart/form-data">
          
          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Hall Name:</label>
              <div class="col-sm-12 col-md-7">
              <select class="form-control" id="hallname" name="hall_id">
                @foreach($halldata as $hall)
                <option value ="{{$hall->id}}">
                  {{$hall->hall_name}}
                </option>
                @endforeach
              </select>
            </div>
          </div> 
           
           <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Event Name:</label>
              <div class="col-sm-12 col-md-7">
              <select class="form-control" id="eventname" name="eventType_id">
                @foreach($eventdata as $event)
                <option value ="{{$event->id}}">
                  {{$event->event_name}}
                </option>
                @endforeach
              </select>
              </div>
          </div> 
         <div class="form-group row mb-4">
  @csrf
  <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Image:</label>
  <div class="col-sm-12 col-md-7">
  <input type="file" name="image" id="image"/>
  </div></div>
          
         <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Description:</label>
              <div class="col-sm-12 col-md-7">
              <textarea class="form-control" id="description" name="description"></textarea>
              
              </div>
        </div>


      
        <div class="form-group row mb-4">
           @csrf
          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name"></label>
            <div class="col-sm-12 col-md-7">
            <button type="submit" class="btn btn-primary">Save</button>
            <input type="button" value="Cancel" class="btn btn-danger" onclick="clearText()"/>
             
            </div>
      </div>
      </form>
  </div>
</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>

<script> 
    $('#description').summernote({
        placeholder:'Hello',
        tabsize: 2,
        height: 100
      });
</script>
<script type="application/javascript">
  function clearText(){
    
    document.getElementById('image').value="";
    $('#description').summernote('code', '');
    
  }
</script>
@endsection

resources/views/admin/eventhall/edit.blade.php
<!-- edit.blade.php -->

@extends('layouts.admin-master')

@section('content')

<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">


<section class="section">
  <div class="section-header">
    <h1>Manage Hall_Events</h1>
  </div>
 <div class="card">
      <!-- card header -->
      <div class="card-header">
        <!-- card title -->
        <h4>Edit Form</h4>
        <div class="card-header-action">
          <a href="{{ route('admin.eventhall')}}" class="btn btn-primary">HallEventList</a>
        </div>
      </div>
      <div class="card-body">
     @if(Session::has('toasts'))
  @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      {{ $toast['message'] }}
    </div>
  @endforeach
@endif

    @if($message = Session::get('info'))
    <div class = "alert alert-info alert-block">
      <strong>{{$message}}</strong>
      </div>
      @endif 
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif

    
        <form method="post" enctype="multipart/form-data" action="{{ route('admin.eventhall_update.update',['id'=>$edit_hallevents->id])}}">

            <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Hall Name:</label>
              <div class="col-sm-12 col-md-7">
              <select class="form-control" name="hall_id">
                @foreach($halldata as $hall)
                <option value="{{$hall->id}}" {{ $hall->id === $edit_hallevents->hall_id ? 'selected' : '' }} >
                  {{$hall->hall_name}}
                </option>
                @endforeach
              </select>
            </div>
          </div> 

            <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Event Name:</label>
              <div class="col-sm-12 col-md-7">
              <select class="form-control" name="eventType_id">
                @foreach($eventdata as $event)
                <option value="{{$event->id}}" {{ $event->id === $edit_hallevents->eventType_id ? 'selected' : '' }} >
                  {{$event->event_name}}
                </option>
                @endforeach
              </select>
            </div>
          </div> 
          
            

          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Description:</label>
              <div class="col-sm-12 col-md-7">
              <textarea class="form-control" id="description" name="description" cols="30" rows="10">{{$edit_hallevents->description}}</textarea>
              </div>
        </div>
         <div class="form-group row mb-4">
          @csrf
          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Event Image:</label>
          <div class="col-sm-12 col-md-7">
          <input type="file" name="image"/>
          <img src="{{URL::to('/')}}/images/{{$edit_hallevents->image}}" class="img-thumbnail" width="100"/>
          <input type="hidden" name="hidden_image" value="{{$edit_hallevents->image}}"/>
        </div></div>


          <div class="form-group row mb-4">
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name"></label>
            <div class="col-sm-12 col-md-7">
              <button type="submit" class="btn btn-primary">Update</button>
            </div>
          </div>
      </form>
  </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>

<script> 
    $('#description').summernote({
        placeholder: 'Hello',
        tabsize: 2,
        height: 100
      });
</script>
@endsection

resources/views/admin/eventhall/index.blade.php
<!-- index.blade.php -->

@extends('layouts.admin-master')

@section('content')
<section class="section">
  <div class="section-header">
    <h1>Manage Hall_Events</h1>
  </div>
 <div class="card">
      <!-- card header -->
      <div class="card-header">
        <!-- card title -->
        <h4>Hall_Event List</h4>
        <div class="card-header-action">
          <a href="{{ route('admin.eventhall.create')}}" class="btn btn-primary">Add<i class="fas fa-plus"></i></a>
        </div>
      </div>
  <div class="card-body">
      @if($message = Session::get('info'))
      <div class = "alert alert-info alert-block">
        <button type = "button" class="close" data-dismiss = "alert">x</button>
        <strong>{{$message}}</strong>
      </div>
      @endif  

       @if(Session::has('toasts'))
        @foreach(Session::get('toasts') as $toast)
        <div class="alert alert-{{ $toast['level'] }}">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

        {{ $toast['message'] }}
        </div>
        @endforeach
        @endif 

        @if(session()->get('success'))
        <div class="alert alert-success">
          {{ session()->get('success') }}  
        </div><br />
        @endif
      <div class="table-responsive">
      <table class="table table-striped">
      <thead>
        <tr>
           <th>Event Image</th>
          <th>Hall Name</th>
          <th>Event Type</th>
          <th colspan="2">Action</th>
        </tr>
      </thead>
      <tbody>
       @foreach($data as $eventhall)
        
        <tr>
           <td><img src="{{URL::to('/')}}/images/{{$eventhall->image}}" class="img-thumbnail" width="100"/></td>
           <td>{{$eventhall->hall_name}}</td>
            <td>{{$eventhall->event_name}}</td>
            <td><a href="javascript:;" data-toggle="modal" onclick="deleteData({{$eventhall->id}})" 
              data-target="#DeleteModal" class="btn btn-danger"><i class="fa fa-trash"></i> </a>
              <a href="{{ route('admin.eventhall.edit',$eventhall->id)}}" class="btn btn-primary"><i class='fas fa-edit'></i></a>  
            </td>
        </tr>
      @endforeach
            
        
      </tbody>
    </table>
  </div>
  </div>
</div>
  </section>


<div id="DeleteModal" class="modal fade " role="dialog">
   <div class="modal-dialog modal-sm">
     <!-- Modal content-->
     <form action="" id="deleteForm" method="post">
         <div class="modal-content">
             <div class="modal-header bg-danger">
              <h6 class="modal-title text-center">DELETE CONFIRMATION</h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                 
             </div>
             <div class="modal-body">
                 {{ csrf_field() }}
                 {{ method_field('DELETE') }}
                 <p class="text-center">Are you sure want to delete ?</p>
             </div>
             <div class="modal-footer">
                 <center>
                     <input type="hidden" name="eventhall_id" id="eventhall_id">
                     <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">OK</button>
                     <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                 </center>
             </div>
         </div>
     </form>
   </div>
 </div>
   <script type="text/javascript">
     function deleteData(id)
     {
         var id = id;
         var url = '{{ route("admin.eventhall.destroy",":eventhall_id") }}';
         url = url.replace(':eventhall_id', id);
         $("#deleteForm").attr('action', url);
         document.getElementById('eventhall_id').vaule =id;
     }

     function formSubmit()
     {
         $("#deleteForm").submit();
     }
  </script>
   <script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>


@endsection