routes/web.php
<?php
use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;

Route::get('/', function() {
    return redirect(route('frontend.homes'));
});

Route::get('/frontend', function() {
    return redirect(route('frontend.homes'));
});
Route::get('/send-mail', function () {
 
    Mail::to('newuser@example.com')->send(new MailtrapExample()); 
 
    return 'A message has been sent to Mailtrap!';
 
});

Route::name('frontend.')->prefix('frontend')->group(function() {

    Route::get('homes', 'frontend\HomesController')->name('homes');
   

    Route::get('eventdetail', 'frontend\EventdetailController@index')->name('eventdetail');
    Route::get('hallabout', 'frontend\HallaboutController@index')->name('hallabout');



    Route::get('contact', 'frontend\ContactController@index')->name('contact');

    Route::get('frontend/admin/dashboard', 'DashboardController@index')->middleware('auth')->name('admin.dashboard');

    Route::get('about', 'frontend\AboutController@index')->name('about');
      Route::get('language', 'frontend\LanguageController@index')->name('language');
    
    Route::get('lang/{locale}', 'frontend\LanguageController@lang');
      
});

Route::get('home', function() {
    return redirect(route('admin.dashboard'));
});

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {

    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
   ]);

    Route::resource('event', 'EventTypeController', [
        'names' => [
            'index' => 'event'
        ]
    ]);
    

    Route::resource('eventhall', 'EventHallController', [
        'names' => [
            'index' => 'eventhall'
        ]
    ]);
     Route::post('event_update', 'EventHallController@update')->name('eventhall_update.update');

   Route::resource('state', 'StateController', [
        'names' => [
            'index' => 'state'
        ]

    ]);
   Route::resource('townships', 'TownshipController', [
        'names' => [
            'index' => 'townships'
        ]
    
    ]);

    Route::resource('city', 'CityController', [
        'names' => [
            'index' => 'city'
        ]
    ]);


    Route::resource('contact','ContactController', [

        'names' => [
            'index' => 'contact'
        ]
    ]);
Route::get('googlemap', 'ContactController@map');

Route::get('googlemap/direction', 'ContactController@direction');

    Route::resource('address', 'AddressController', [
        'names' => [
            'index' => 'address'
                
        ]
    ]);
        

    Route::resource('hall', 'HallController', [
        'names' => [
            'index' => 'hall'
        ]
    ]);
    
    Route::post('hall_update', 'HallController@update')->name('hall_update.update');



 });







Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

Route::name('js.')->group(function() {
    Route::get('dynamic.js', 'JsController@dynamic')->name('dynamic');
});

// Get authenticated user
Route::get('users/auth', function() {
    return response()->json(['user' => Auth::check() ? Auth::user() : false]);
});

app/Http/Controllers/AddressController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Http\Request;
use App\MyLibs\Repositories\AddressRepository;


class AddressController extends Controller
{
      public function __construct(AddressRepository $addressRepo)
    {
        	$this->addressRepo=$addressRepo;
    }

    	public function create()
        {
          return view ('admin.address.create') ;
        }
    	public function store(Request $request)
       { 
         $validatedData = $request->validate([
              'address' => 'required|max:255',
              'phone' => 'required|numeric|unique:addresses|min:11',
              'email' => 'required|email|unique:addresses',
              
        ]);
        $data = $request->all();

         if(isset($request->status))
         {
           $data['status']=1;

           $sql = "update addresses set status=0";
           $result = \DB::select($sql);
         }else{

           $data['status'] =0;

         }

        //    if($request->get('status') == null){
        //     $status = 0;
        //     $data['status'] =0;
        // }
        // else{
        //     $status = 1;
        //     $data['status']=1;
        // }
           
        

        	

    	   
    	    $this->addressRepo->create($data);
    	   	
    	    return back()->with('info','Address is sucessfully save!');
           return redirect()->back()->withInput();
       }
      public function index()
    	   {
    	    	$address=$this->addressRepo->getAll();
    	    	return view('admin.address.index',compact('address'));
    	   }
      public function edit(Request $request,$id)
         {      
              if ($request->get('status') == 'on') {
                  $edit_address->status = 1;
            
              } elseif ($request->get('status') == 'off') {
                  $edit_address->status = 0;
                 } 
 
               $edit_address=$this->addressRepo->getById($id);
               return view('admin.address.edit',compact('edit_address'));
	       }
         

         public function show($id,Request $request)
           { 
            $request['status'] = isset($request['status']) ? "1":"0";

            $data = $request->all();
            if($data['status'] == 1)
            {
               $sql = "update addresses set status=0";
               $result = \DB::select($sql);
            }                                                                                                                             
           $this->addressRepo->update($data,$id);
           return redirect()->back()->with('info','Address  is successfully updated');
           return redirect()->back()->withInput();
           }

      public function destroy($address_id)
        {
        
        $this->addressRepo->delete($address_id);
        return back()->with('info','address is sucessfully delete!');
         return redirect()->back()->withInput();
            
      }

}
	   

resources/views/admin/address/create.blade.php
@extends('layouts.admin-master')
@section('content')
<section class="section">
  <div class="section-header">
    <h1> Manage Address</h1>
  </div>
  <div class="section-body">

    <div class="card">
      <!-- card header -->
      <div class="card-header">
        <h4>Add New Address</h4>
        <div class="card-header-action" >
        <a href="{{route('admin.address')}}" class="btn btn-primary">AddressList</a>
        </div>
      </div>
  <div class="card-body">
    
 @if(Session::has('toasts'))
  @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

      {{ $toast['message'] }}
    </div>
  @endforeach
@endif

    @if($message=Session::get('info'))
    <div class="alert alert-info alert-block">
    <button type ="button" class="close" data-dismiss="alert">x</button>
    <strong>{{$message}}</strong>
    </div>
    @endif

    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
         </ul>
      </div><br/> 
    @endif
      

  <form method="post" action="{{ route('admin.address.store') }}">
     @csrf

 <div class="form-group row mb-4">
  <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Address</label>
  <div class="col-sm-12 col-md-7">
  <input type="text" class="form-control" id="address" placeholder="Enter Address" name="address">
</div></div>

<div class="form-group row mb-4">
  <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Phnoe</label>
  <div class="col-sm-12 col-md-7">
  <input type="text" class="form-control" id="phone" placeholder="Enter Phone" name="phone">
</div></div>

<div class="form-group row mb-4">
  <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
  <div class="col-sm-12 col-md-7">
  <input type="text" class="form-control" id="email" placeholder="Enter Email" name="email">
</div></div>

<div class="form-group row mb-4">
  <lable class="col-form-label text-md-right col-12 col-md-3 col-lg-3" from="">Status</lable>
  <div class="col-sm-12 col-md-7">
   <input type="checkbox" name="status" value="1" 

{{isset($address['status'])&&$address['status']=='1' ? 'checked' : ''}}> 
 </div> 
</div>  


<div class="form-group row mb-4">
  <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
  <div class="col-sm-12 col-md-7"><button type="submit" class="btn btn-primary">Save</button>
  <input type="button" value="Cancle" class="btn btn-danger" onclick="clearText()" /> 
</div>
</div>

  </div>

  </form>
  </div> 
  </div>
</div>
  <script>
  function clearText() {
  document.getElementById('address').value="";
  document.getElementById('phone').value="";
  document.getElementById('email').value="";
    document.getElementById('status').value="";
   }
  </script>
  <script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>
</section>
@endsection

resources/views/admin/address/edit.blade.php
@extends('layouts.admin-master')

@section('content')

<section class="section">
  <div class="section-header">

    <h1>Manage Address</h1>
  </div>
 <div class="card">
      <div class="card-header">
        <h4>Edit Form</h4>
        <div class="card-header-action">
          <a href="{{ route('admin.address')}}" class="btn btn-primary">AddressList</a></div>
      </div>
  <div class="section-body">
   <div class="card">
    <div class="card-body">
    

    @if(Session::has('toasts'))
    @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

      {{ $toast['message'] }}
    </div>
    @endforeach
    @endif

     @if($message=Session::get('info'))
    <div class="alert alert-info alert-block">
    <button type ="button" class="close" data-dismiss="alert">x</button>
    <strong>{{$message}}</strong>
    </div>
    @endif 

  
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
    <form method="put" action="{{route('admin.address.update',['id'=>$edit_address->id])}}">
       @csrf
     <div class="form-group row mb-4">
            
         <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Address</label>
         <div class="col-sm-12 col-md-7">
         <input type="text" class="form-control" name="address" value="{{$edit_address->address}}"/>
       </div>
     </div>


     <div class="form-group row mb-4">
            
         <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Phone</label>
         <div class="col-sm-12 col-md-7">
         <input type="text" class="form-control" name="phone" value="{{$edit_address->phone}}"/>
       </div>
     </div>

     <div class="form-group row mb-4">
            
         <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
         <div class="col-sm-12 col-md-7">
         <input type="text" class="form-control" name="email" value="{{$edit_address->email}}"/>
       </div>
     </div>


      <div class="form-group row mb-4">
       <lable class="col-form-label text-md-right col-12 col-md-3 col-lg-3" from="">Status</lable>
         <div class="col-sm-12 col-md-7">
      
          @if($edit_address->status == 1)
            <input type="checkbox" name="status" value="1"{{isset($address['status'])&&$address['status']=='1' ? 'checked' : ''}}  checked>
          @else
            <input type="checkbox" name="status" value="0"{{isset($address['status'])&&$address['status']=='0' ? '' : 'notchecked'}} >
                    
          @endif
             
        </div> 
      </div> 

       <div class="form-group row mb-4">
         <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
         <div class="col-sm-12 col-md-7">
          <button type="submit" class="btn btn-primary">Update</button>
        </div>
      </div>
      </form>
  </div>
</div></div></div>
<script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>
@endsection

resources/views/admin/address/index.blade.php
@extends('layouts.admin-master')

@section('content')

<section class="section">
  <div class="section-header">
    <h1>Manage Address</h1>
  </div>
<div class="card">
      <!-- card header -->
      <div class="card-header">
        <h4>Address List</h4>
        <div class="card-header-action" >
        <a href="{{route('admin.address.create')}}" class="btn btn-primary">Add <i class="fas fa-plus"></i></a>
       </div> 
     </div>
 <div class="card-body">
     @if($message = Session::get('info'))
      <div class = "alert alert-info alert-block">
      <button type = "button" class="close" data-dismiss = "alert">x</button>
      <strong>{{$message}}</strong>
      </div>
      @endif  

       @if(Session::has('toasts'))
         @foreach(Session::get('toasts') as $toast)
            <div class="alert alert-{{ $toast['level'] }}">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

           {{ $toast['message'] }}
            </div>
      @endforeach
        @endif     
 
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
<div style="width:100%;height:100%;overflow-x: scroll;overflow-y:hidden";>
 <table class="table table-striped table-bordered" >
    <thead>
        <tr>
            
          <th>Address</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Status</th>
          
          

          <th colspan="4">Action</th>

        </tr>
    </thead>
    <tbody>
        @foreach($address as $address)
          <tr>
            <td>{{$address->address}}</td>
            <td>{{$address->phone}}</td>
            <td>{{$address->email}}</td>
            <td>@if ($address->status == 1)
                 <i align="center" style="text-align:center; font-size:150%; font-weight:bold; color:green;" class="fas fa-check"></i>
                @else 
                 <i align="center" style="text-align:center; font-size:150%; font-weight:bold; color:red;" class="fas fa-times"></i>
                @endif
                
                      
            </td>
            <td>
              <a href="javascript:;" data-toggle="modal" onclick="deleteData({{$address->id}})" data-target="#DeleteModal" class="btn btn-danger"><i class="fa fa-trash"></i> </a>
              
              <a href="{{ route('admin.address.edit',$address->id)}}" class="btn btn-primary"><i class='fas fa-edit'></i></a>   
            
          </td>
        </tr>
      @endforeach
    </div>
    </tbody>
  </table>
</div>

</section>

  

  
<div id="DeleteModal" class="modal fade " role="dialog">
   <div class="modal-dialog modal-sm">
     <!-- Modal content-->
     <form action="" id="deleteForm" method="post">
         <div class="modal-content">
             <div class="modal-header bg-danger">
              <h6 class="modal-title text-center">DELETE CONFIRMATION</h6>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                 
             </div>
             <div class="modal-body">
                 {{ csrf_field() }}
                 {{ method_field('DELETE') }}
                 <p class="text-center">Are you sure want to delete ?</p>
             </div>
             <div class="modal-footer">
                 <center>
                     <input type="hidden" name="address_id" id="address_id">
                     <button type="submit" name="" class="btn btn-danger" data-dismiss="modal" onclick="formSubmit()">OK</button>
                     <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                 </center>
             </div>
         </div>
     </form>
   </div>
 </div>
  


    <script type="text/javascript">
     function deleteData(id)
     {
         var id = id;
         var url = '{{ route("admin.address.destroy", ":address_id") }}';
         url = url.replace(':address_id', id);
         $("#deleteForm").attr('action', url);
         document.getElementById('address_id').value = id;
     }

     function formSubmit()
     {
         $("#deleteForm").submit();
     }
  </script>

  <script src="{{ asset('js/app.js') }}?{{ uniqid() }}"></script>


  

@endsection