routes/web.php
<?php
use App\Mail\MailtrapExample;
use Illuminate\Support\Facades\Mail;

Route::get('/', function() {
    return redirect(route('frontend.homes'));
});

Route::get('/frontend', function() {
    return redirect(route('frontend.homes'));
});
Route::get('/send-mail', function () {
 
    Mail::to('newuser@example.com')->send(new MailtrapExample()); 
 
    return 'A message has been sent to Mailtrap!';
 
});

Route::name('frontend.')->prefix('frontend')->group(function() {

    Route::get('homes', 'frontend\HomesController')->name('homes');
   

    Route::get('eventdetail', 'frontend\EventdetailController@index')->name('eventdetail');
    Route::get('hallabout', 'frontend\HallaboutController@index')->name('hallabout');



    Route::get('contact', 'frontend\ContactController@index')->name('contact');

    Route::get('frontend/admin/dashboard', 'DashboardController@index')->middleware('auth')->name('admin.dashboard');

    Route::get('about', 'frontend\AboutController@index')->name('about');
      Route::get('language', 'frontend\LanguageController@index')->name('language');
    
    Route::get('lang/{locale}', 'frontend\LanguageController@lang');
      
});

Route::get('home', function() {
    return redirect(route('admin.dashboard'));
});

Route::name('admin.')->prefix('admin')->middleware('auth')->group(function() {

    Route::get('dashboard', 'DashboardController')->name('dashboard');

    Route::get('users/roles', 'UserController@roles')->name('users.roles');
    Route::resource('users', 'UserController', [
        'names' => [
            'index' => 'users'
        ]
   ]);

    Route::resource('event', 'EventTypeController', [
        'names' => [
            'index' => 'event'
        ]
    ]);
    

    Route::resource('eventhall', 'EventHallController', [
        'names' => [
            'index' => 'eventhall'
        ]
    ]);
     Route::post('event_update', 'EventHallController@update')->name('eventhall_update.update');

   Route::resource('state', 'StateController', [
        'names' => [
            'index' => 'state'
        ]

    ]);
   Route::resource('townships', 'TownshipController', [
        'names' => [
            'index' => 'townships'
        ]
    
    ]);

    Route::resource('city', 'CityController', [
        'names' => [
            'index' => 'city'
        ]
    ]);


    Route::resource('contact','ContactController', [

        'names' => [
            'index' => 'contact'
        ]
    ]);
Route::get('googlemap', 'ContactController@map');

Route::get('googlemap/direction', 'ContactController@direction');

    Route::resource('address', 'AddressController', [
        'names' => [
            'index' => 'address'
                
        ]
    ]);
        

    Route::resource('hall', 'HallController', [
        'names' => [
            'index' => 'hall'
        ]
    ]);
    
    Route::post('hall_update', 'HallController@update')->name('hall_update.update');



 });







Route::middleware('auth')->get('logout', function() {
    Auth::logout();
    return redirect(route('login'))->withInfo('You have successfully logged out!');
})->name('logout');

Auth::routes(['verify' => true]);

Route::name('js.')->group(function() {
    Route::get('dynamic.js', 'JsController@dynamic')->name('dynamic');
});

// Get authenticated user
Route::get('users/auth', function() {
    return response()->json(['user' => Auth::check() ? Auth::user() : false]);
});

app/Http/Controllers/HallController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\MyLibs\Repositories\CityRepository;
use App\MyLibs\Repositories\StateRepository;
use App\MyLibs\Repositories\TownshipRepository;
use App\MyLibs\Repositories\HallRepository;
use Illuminate\Support\Facades\DB;
use App\MyLibs\Models;


class HallController extends Controller
{
    public function __construct(HallRepository $hallRepo,StateRepository $stateRepo,CityRepository $cityRepo,TownshipRepository $townshipRepo){
    		$this->hallRepo=$hallRepo;
    		$this->cityRepo=$cityRepo;
    		$this->stateRepo=$stateRepo;
    		$this->townshipRepo=$townshipRepo;
  }

    public function index()
        {
           $data=DB::table('halls')
           		->join('states','states.id','=','halls.state_id')
           		->join('cities','cities.id','=','halls.city_id')
           		->join('townships','townships.id','=','halls.township_id')
           		->select('halls.id','halls.hall_image','halls.hall_name','halls.phone_no','halls.open_time','halls.close_time','states.state_name','cities.city_name','townships.township_name','halls.address')
           		->get();
           return view('admin.hall.index', compact('data'));
        }

    public function create(){

          $statedata = [];
          $statedata =$this->stateRepo->getAll();
         
          $citydata = [];
          $citydata =$this->cityRepo->getAll();

          $townshipdata = [];
          $townshipdata =$this->townshipRepo->getAll();

          return view('admin.hall.create',compact('statedata','citydata','townshipdata'));
          
    }

    public function store(Request $request)
       {
          $validatedData=$request->validate([
          'hall_name' => 'required',
          'phone_no' => 'required|unique:halls',
          'open_time' => 'required',
          'close_time' => 'required',
          'address' => 'required',
          'hall_image' => 'required',
        ]);

          $image = $request->file('hall_image');
          $new_name=rand() . '.' . $image->getClientOriginalExtension();
          $image->move(public_path('images'),$new_name);
          $form_data=array(
            'hall_name'=>$request->hall_name,
            'phone_no'=>$request->phone_no,
            'open_time'=>$request->open_time,
            'close_time'=>$request->close_time,
            'state_id'=>$request->state_id,
            'city_id'=>$request->city_id,
            'township_id'=>$request->township_id,
            'address'=>$request->address,
            'hall_image'=>$new_name
            );
          $state_id= explode(':',$form_data['state_id']);
          $city_id= explode(':',$form_data['city_id']);
          $township_id=explode(':',$form_data['township_id']);

          $form_data['state_id'] = $state_id[1];
          $form_data['city_id'] = $city_id[1];
          $form_data['township_id'] = $township_id[1];

          $this->hallRepo->create($form_data);
          return back()->with('info','Hall is sucessfully save!');
          return redirect()->back()->withInput();
       }


      public function edit($hall_id)
      {
       
       $statedata = [];
       $statedata =$this->stateRepo->getAll();

       $citydata = [];
        $citydata =$this->cityRepo->getAll();

        $townshipdata = [];
        $townshipdata =$this->townshipRepo->getAll();
          

       $edit_halls=$this->hallRepo->getById($hall_id);
       
       return view('admin.hall.edit',compact('edit_halls','statedata','citydata','townshipdata'));
         
      }

  

    public function update(Request $request)
    {
      $hall_id=$request->id;
      $image_name=$request->hidden_image;
      $image=$request->file('hall_image');

      if($image==''){
          $form_data=array(
            'hall_name'=>$request->hall_name,
            'phone_no'=>$request->phone_no,
            'open_time'=>$request->open_time,
            'close_time'=>$request->close_time,
            'state_id'=>$request->state_id,
            'city_id'=>$request->city_id,
            'township_id'=>$request->township_id,
            'address'=>$request->address,
            'hall_image'=>$image_name
          );
      }

      if($image!=''){
          $imagenew=rand().'.'.$image->getClientOriginalExtension();
          $image->move(public_path('images'),$imagenew);
          $image_path = public_path().'/images/'.$image_name;

          unlink($image_path);
          $this->hallRepo->delete($image_name);
          $form_data=array(
            'hall_name'=>$request->hall_name,
            'phone_no'=>$request->phone_no,
            'open_time'=>$request->open_time,
            'close_time'=>$request->close_time,
            'state_id'=>$request->state_id,
            'city_id'=>$request->city_id,
            'township_id'=>$request->township_id,
            'address'=>$request->address,
            'hall_image'=>$imagenew
            );
        }

        
          $state_id= explode(':',$form_data['state_id']);
          $city_id= explode(':',$form_data['city_id']);
          $township_id=explode(':',$form_data['township_id']);

          $form_data['state_id'] = $state_id[1];
          $form_data['city_id'] = $city_id[1];
          $form_data['township_id'] = $township_id[1];

          $form_data=array_except($form_data,['$hall_id']);
          $this->hallRepo->update($form_data,$hall_id);

        return back()->with('info','Hall is successfully update!');
        return redirect()->back()->withInput();
    } 

    public function destroy($hall_id)
    {

      $data=$this->hallRepo->getById($hall_id);

       $image_name=$data->hall_image;
      $image_path = public_path().'/images/'.$image_name;
       unlink($image_path);

      $this->hallRepo->delete($hall_id,$image_name);
      return back()->with('info','Hall is successfully delete!');
      return redirect()->back()->withInput();
    }
}

resources/views/admin/hall/create.blade.php
@extends('layouts.hall-master')


@section('title')
Manage Halls
@endsection 

@section('content')
<div ng-app="myApp" ng-controller="myCtrl">
<section class="section">
  <div class="section-header">
    <h1>Manage Halls</h1>
  </div>
  <div class="section-body">
    <div class="card">

      <div class="card-header">
        
        <h4>Add a New Hall</h4>
        <div class="card-header-action" >
        <a href="{{route('admin.hall')}}" class="btn btn-primary">HallList</a>
        </div>
      </div>
      <!-- card header -->
     
      <!-- card body -->
      <div class="card-body">
        @if(Session::has('toasts'))
        @foreach(Session::get('toasts') as $toast)
        <div class="alert alert-{{ $toast['level'] }}">
            {{ $toast['message'] }}
        </div>
        @endforeach
        @endif

    @if($message=Session::get('info'))
    <div class="alert alert-info alert-block">
    
    <strong>{{$message}}</strong>
  </div>
  @endif

    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
         </ul></div><br/> 
    @endif
      <form  method="post" action="{{route('admin.hall.store')}}" enctype="multipart/form-data">
        
        <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Hall Name:</label>
              <div class="col-sm-12 col-md-7">
               <input type="text" class="form-control" id="hall_name" name="hall_name" placeholder="Enter Hall Name"/>
          </div></div>

          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">State Name:</label>
              <!-- <div class="col-sm-12 col-md-7">
              <select class="form-control" name="state_id">
                @foreach($statedata as $state)
                <option value="{{$state->id}}">
                  {{$state->state_name}}
                </option>
                @endforeach
              </select>
          </div></div>  --> 
              <div class="col-sm-12 col-md-7">
              <select ng-model="selectedState" id="state" name="state_id" value="selectedState" ng-change="selectChange()" ng-options="state.id as state.state_name for state in states" class="form-control">
              </select>
          </div></div>
          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">City Name:</label>
              <!-- <div class="col-sm-12 col-md-7">
              <select class="form-control" name="city_id">
                @foreach($citydata as $city)
                <option value ="{{$city->id}}">>

                  {{$city->city_name}}
                </option>
                @endforeach
              </select>
          </div></div> -->
      <div class="col-sm-12 col-md-7">
        <select ng-model="selectedCity" id="city" name="city_id" ng-change="select()" value="selectedCity" ng-options="city.id as city.city_name for city in cities" class="form-control">
        </select>
      </div></div>

          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Township Name:</label>
              <!-- <div class="col-sm-12 col-md-7">
              <select class="form-control" name="township_id">
                @foreach($townshipdata as $township)
                <option value ="{{$township->id}}">
                  {{$township->township_name}}
                </option>
                @endforeach
              </select>
          </div> </div> -->
            <div class="col-sm-12 col-md-7">
            <select ng-model="selectedTownship" id="township" name="township_id" value="selectedTownship" ng-options="township.id as township.township_name for township in townships" class="form-control">
            </select>
          </div></div>
 
          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Phone No:</label>
              <div class="col-sm-12 col-md-7">
               <input type="text" class="form-control" id="phone_no" 
               name="phone_no" placeholder="Enter Phone No"/>
          </div></div>

            

  <div class="form-group row mb-4">
    @csrf
        <label for="open" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Open Time</label>
        <div class="col-sm-12 col-md-7">
          <div class='input-group date' id='example1'>
              <input type='text' id="open_time" name="open_time" class="form-control" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </span>
          </div>
      </div>
  </div>


  <div class="form-group row mb-4">
    @csrf
        <label for="close" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Close Time</label>
        <div class="col-sm-12 col-md-7">
          <div class='input-group date' id='example2'>
              <input type='text' id="close_time" name="close_time" class="form-control" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </span>
          </div>
      </div>
  </div>

      <div class="form-group row mb-4">
      @csrf
        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Address:</label>
        <div class="col-sm-12 col-md-7">
        <textarea class="form-control" id="address" name="address" placeholder="Enter Hall Address"></textarea> 
      </div></div>

      <div class="form-group row mb-4">
          @csrf
          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Hall Image:</label>
          <div class="col-sm-12 col-md-7">
            <input type="file" name="hall_image" id="hall_image"/>
          </div></div>
 

      <div class="form-group row mb-4">
      @csrf
        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">
        </label>
        <div class="col-sm-12 col-md-7">
        <button type="submit" class="btn btn-primary">Save</button>
        <input type="button" value="Cancel" class="btn btn-danger" onclick="clearText()"/>
      </div></div>
      </form>
  </div>
</div></div></section></div>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script>
var states={!! json_encode($statedata) !!};
var cities={!! json_encode($citydata) !!};
var townships={!! json_encode($townshipdata) !!};

var app = angular.module('myApp', []);
app.config(function($interpolateProvider){
  $interpolateProvider.startSymbol('<%').endSymbol('%>');
});

app.controller('myCtrl', function($scope, $http) {

$scope.states= states;
$scope.cities = cities;
$scope.townships=townships;

$scope.selectedState = $scope.states[0].id;
$scope.selectedCity = $scope.cities[0].id;
$scope.selectedTownship = $scope.townships[0].id;





$http({
          method : "GET",
          url : "/api/v1/get_all?state_id="+$scope.selectedState,
        }).then(function mySuccess(response) {
           $scope.cities = response.data.data.city;
          $scope.townships=response.data.data.township;
          }, function myError(response) {
            $scope.cities = [];
           $scope.townships=[];

        });

$scope.selectChange = function(){

    $http({
          method : "GET",
          url : "/api/v1/get_all?state_id="+$scope.selectedState,
        }).then(function mySuccess(response) {
           $scope.cities = response.data.data.city;
           $scope.selectedCity = $scope.cities[0].id;
           $scope.townships=response.data.data.township;
           $scope.selectedTownship = $scope.townships[0].id;
          }, function myError(response) {

            $scope.cities = [];
           $scope.townships = [];

        });

  }
  
  $http({
          method : "GET",
          url : "/api/v1/get_township?state_id="+$scope.selectedState+"&city_id="+$scope.selectedCity,
        }).then(function mySuccess(response) {
           $scope.townships = response.data.data;
          }, function myError(response) {

            $scope.townships = [];

        });

  

 $scope.select = function(){

    $http({
          method : "GET",
          url : "/api/v1/get_township?state_id="+$scope.selectedState+"&city_id="+$scope.selectedCity,
          
        }).then(function mySuccess(response) {
           $scope.townships = response.data.data;
           $scope.selectedTownship = $scope.townships[0].id;
          }, function myError(response) {

            $scope.townships = [];
        });
  }



});

</script>

<script type="application/javascript">
  function clearText(){
    document.getElementById('image').value="";
    document.getElementById('hall_name').value="";
    document.getElementById('phone_no').value="";
    document.getElementById('open_time').value="";
    document.getElementById('close_time').value="";
    document.getElementById('address').value="";
    /*document.getElementById('state').value="";
    document.getElementById('city').value="";
    document.getElementById('township').value="";
*/
  }
</script>

<script type="application/javascript">
            $(function () {
                $('#example1').datetimepicker({
                    format: 'LT'
                });
            });
</script>

<script type="application/javascript">
            $(function () {
                $('#example2').datetimepicker({
                    format: 'LT'
                });
            });
</script>

@endsection 

resources/views/admin/hall/edit.blade.php
@extends('layouts.hall-master')

@section('content')
<div ng-app="myApp" ng-controller="myCtrl">
<section class="section">
  <div class="section-header">
    <h1>Manage Halls</h1>
  </div>
 <div class="card">
      <!-- card header -->
      <div class="card-header">
        <!-- card title -->
        <h4>Update Hall</h4>
        <div class="card-header-action" >
        <a href="{{route('admin.hall')}}" class="btn btn-primary">HallList</a>
        </div>
      </div>
      <div class="card-body">
     @if(Session::has('toasts'))
  @foreach(Session::get('toasts') as $toast)
    <div class="alert alert-{{ $toast['level'] }}">
      {{ $toast['message'] }}
    </div>
  @endforeach
@endif

    @if($message = Session::get('info'))
    <div class = "alert alert-info alert-block">
      <strong>{{$message}}</strong>
      </div>
      @endif 
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif

        <form method="post" enctype="multipart/form-data" action="{{ route('admin.hall_update.update',['id'=>$edit_halls->id])}}">
          
            <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Hall Name:</label>
              <div class="col-sm-12 col-md-7">
               <input type="text" class="form-control" id="hall_name" name="hall_name" value="{{$edit_halls->hall_name}}"/>
          </div></div>

          

            

          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">State Name:</label>
              <!-- <div class="col-sm-12 col-md-7">
              <select class="form-control" name="state_id">
                @foreach($statedata as $state)
                <option value="{{$state->id}}" {{$state->id === $edit_halls->state_id ? 'selected':''}}>
                  {{$state->state_name}}
                </option>
                @endforeach
              </select>
          </div></div>  -->
          <div class="col-sm-12 col-md-7">
            <select ng-model="selectedState" name="state_id" value="selectedState" ng-change="selectChange()" ng-options="state.id as state.state_name for state in states" class="form-control">
            </select>
          </div></div>

        <div class="form-group row mb-4">
          @csrf
          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">City Name:</label>
          <div class="col-sm-12 col-md-7">
            <select ng-model="selectedCity" name="city_id" ng-change="select()" value="selectedCity" ng-options="city.id as city.city_name for city in cities" class="form-control">
            </select>
        </div></div>

          <div class="form-group row mb-4"> 
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Township Name:</label>
              <!-- <div class="col-sm-12 col-md-7">
              <select class="form-control" name="township_id">
                @foreach($townshipdata as $township)
                <option value ="{{$township->id}}" {{$township->id === $edit_halls->township_id?'selected':''}}>
                  {{$township->township_name}}
                </option>
                @endforeach
              </select>
          </div> </div> -->
          <div class="col-sm-12 col-md-7">
            <select ng-model="selectedTownship" name="township_id" value="selectedTownship" ng-options="township.id as township.township_name for township in townships" class="form-control">
            </select>
          </div></div>
          
          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Phone No:</label>
              <div class="col-sm-12 col-md-7">
              <input type="text" class="form-control" id="phone_no" 
               name="phone_no" value="{{$edit_halls->phone_no}}" />
          </div></div>



        <div class="form-group row mb-4">
          @csrf
        <label for="close" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Open Time</label>
        <div class="col-sm-12 col-md-7">
          <div class='input-group date' id='example1'>
              <input type='text' id="open_time" name="open_time" value="{{$edit_halls->open_time}}" class="form-control" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </span>
          </div>
      </div>
  </div>


      <div class="form-group row mb-4">
          @csrf
        <label for="close" class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Close Time</label>
        <div class="col-sm-12 col-md-7">
          <div class='input-group date' id='example2'>
              <input type='text' id="close_time" name="close_time" value="{{$edit_halls->close_time}}" class="form-control" />
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-time"></span>
              </span>
          </div>
      </div>
  </div>
           
          
          <div class="form-group row mb-4">
              @csrf
              <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Address:</label>
              <div class="col-sm-12 col-md-7">
               <textarea class="form-control" id="address" name="address">{{$edit_halls->address}}</textarea> 
             </div></div>

        <div class="form-group row mb-4">
          @csrf
          <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3" for="name">Hall Image:</label>
          <div class="col-sm-12 col-md-7">
          <input type="file" name="hall_image"/>
          <img src="{{URL::to('/')}}/images/{{$edit_halls->hall_image}}" class="img-thumbnail" width="100"/>
          <input type="hidden" name="hidden_image" value="{{$edit_halls->hall_image}}"/>
        </div></div>

        
          <div class="form-group row mb-4">
              @csrf
            <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
            <div class="col-sm-12 col-md-7">
            <button type="submit" class="btn btn-primary">Update</button>
          </div></div>     
      </form>
  </div>
</div></section></div>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
<script>
var states={!! json_encode($statedata) !!};
var cities={!! json_encode($citydata) !!};
var townships={!! json_encode($townshipdata) !!};
var edit_halls={!! json_encode($edit_halls) !!};
var app = angular.module('myApp', []);
app.config(function($interpolateProvider){
  $interpolateProvider.startSymbol('<%').endSymbol('%>');
}); 

app.controller('myCtrl', function($scope, $http) {

$scope.states= states;
$scope.cities = cities;
$scope.townships=townships;
$scope.edit_halls=edit_halls;

$scope.selectedState = $scope.edit_halls.state_id;
$scope.selectedCity = $scope.edit_halls.city_id;
$scope.selectedTownship = $scope.edit_halls.township_id;

$http({
          method : "GET",
          url : "/api/v1/get_alledit?state_id="+$scope.selectedState+"&city_id="+$scope.selectedCity,
        }).then(function mySuccess(response) {
           $scope.cities = response.data.data.city;
          $scope.townships=response.data.data.township;

          }, function myError(response) {
            $scope.cities = [];
           $scope.townships=[];

        });

$scope.selectChange = function(){

    $http({
          method : "GET",
          url : "/api/v1/get_all?state_id="+$scope.selectedState,
        }).then(function mySuccess(response) {
           $scope.cities = response.data.data.city;
           $scope.selectedCity = $scope.cities[0].id;
           
           $scope.townships=response.data.data.township;
           $scope.selectedTownship = $scope.townships[0].id;
          }, function myError(response) {

            $scope.cities = [];
           $scope.townships=[];

        });

  }
  
 $http({
          method : "GET",
          url : "/api/v1/get_township?state_id="+$scope.selectedState+"&city_id="+$scope.selectedCity,
        }).then(function mySuccess(response) {
           $scope.townships = response.data.data;
          }, function myError(response) {

            $scope.townships = [];

        });

  

 $scope.select = function(){

    $http({
          method : "GET",
          url : "/api/v1/get_township?state_id="+$scope.selectedState+"&city_id="+$scope.selectedCity,
          
        }).then(function mySuccess(response) {
           $scope.townships = response.data.data;
           $scope.selectedTownship = $scope.townships[0].id;
          }, function myError(response) {

            $scope.townships = [];
        });
  }



});

</script>
<script type="application/javascript">
            $(function () {
                $('#example1').datetimepicker({
                    format: 'LT'
                });
            });
        </script>

<script type="application/javascript">
            $(function () {
                $('#example2').datetimepicker({
                    format: 'LT'
                });
            });
        </script>

@endsection